version: '1.0'
services:
  app:
    build: .
    container_name: cloudspace_app
    volumes:
      - .:/app
    networks:
      net:
        ipv4_address: 172.16.1.10
    ports:
      - "8800:8000"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    container_name: cloudspace_cache
    networks:
      net:
        ipv4_address: 172.16.1.11
    ports:
      - "6379:6379"
    volumes:
      - cldspcRd:/data

  postgres:
    image: postgres:latest
    container_name: cloudspace_db
    networks:
      net:
        ipv4_address: 172.16.1.12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cloudspace_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cloudspace_db
    volumes:
      - cldspcPg:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cloudspace_pgadmin
    networks:
      net:
        ipv4_address: 172.16.1.13
    ports:
      - "5500:80"  # PgAdmin UI
    environment:
      - PGADMIN_DEFAULT_EMAIL=suyashmadhesia@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Wonderful@123
    volumes:
      - cldspcPgadmin:/var/lib/pgadmin

volumes:
  cldspcRd:
  cldspcPg:
  cldspcPgadmin:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
