version: '1.0'
services:
  app:
    build: .
    container_name: cloudspace_app
    volumes:
      - .:/app
    networks:
      net:
        ipv4_address: 172.16.1.10
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    container_name: cloudspace_cache
    networks:
      net:
        ipv4_address: 172.16.1.11
    ports:
      - "6501:6379"
    volumes:
      - cldspcRd:/data

  postgres:
    image: postgres:latest
    container_name: cloudspace_db
    networks:
      net:
        ipv4_address: 172.16.1.12
    ports:
      - "6500:5432"
    environment:
      - POSTGRES_USER=cloudspace_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cloudspace_db
    volumes:
      - cldspcPg:/var/lib/postgresql/data

volumes:
  cldspcRd:
  cldspcPg:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
