services:
  redis:
    image: redis:latest
    container_name: cloudspace_cache
    networks:
      net:
        ipv4_address: 172.16.1.11
    ports:
      - "6380:6379"
    volumes:
      - cldspcRd:/data

  postgres:
    image: postgres:latest
    container_name: cloudspace_db
    networks:
      net:
        ipv4_address: 172.16.1.12
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=cloudspace_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cloudspace_db
    volumes:
      - cldspcPg:/var/lib/postgresql/data
  
  neo:
    image: neo4j:latest
    container_name: cloudspace_neo_db
    networks:
      net:
        ipv4_address: 172.16.1.13
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/Wonderful123
    volumes:
      - cldspcNeo:/var/lib/neo4j/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cloudspace_pgadmin
    networks:
      net:
        ipv4_address: 172.16.1.14
    ports:
      - "5500:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=suyashmadhesia@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Wonderful@123
    volumes:
      - cldspcPgadmin:/var/lib/pgadmin
  
  app:
    build: .
    container_name: cloudspace_app
    volumes:
      - .:/app
    networks:
      net:
        ipv4_address: 172.16.1.10
    ports:
      - "8800:8000"
    depends_on:
      - redis
      - postgres


volumes:
  cldspcRd:
  cldspcPg:
  cldspcPgadmin:
  cldspcNeo:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
